# ===================== BANCO RELACIONAL - H2 =====================
spring.datasource.url=jdbc:h2:mem:tarefasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===================== BANCO RELACIONAL - MariaDB =====================
# spring.datasource.url=jdbc:mariadb://localhost:3306/tarefasdb
# spring.datasource.username=seu_usuario
# spring.datasource.password=sua_senha
# spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# ===================== BANCO NO-SQL - MongoDB =====================
# spring.data.mongodb.uri=mongodb://localhost:27017/tarefasdb

spring.jpa.hibernate.ddl-auto=update
